pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/balahussain9640/Jenkins-Zero-To-Hero.git'
            }
        }
        stage('Build') {
            steps {
                script {
                    sh 'mvn clean install'
                }
            }
        }
        stage('Test') {
            steps {
                // You can add testing steps here
                echo 'Running tests...'
            }
        }
        stage('Docker Test') {
            agent {
                docker { image 'node:16-alpine' }
            }
            steps {
                sh 'node --version'
            }
        }
    }
}
